# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dev Practical
tagline:          'Practice HTML and CSS
description:      'Choose from the list of practical projects to learn and practice HTML and CSS. Learn how to create a project from zero to publishing it online.'
url:              https://devpractical.com
baseurl:          /

author:
  name:           'Avic Ndugu'
  url:            https://twitter.com/avic-ndugu

paginate:         25
paginate_path:    "blog/page:num/"

include: 
  - _redirects
# Custom vars
# version:          2.1.0

# github:
  # repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown
