# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Journeyman Hacker
tagline:          'Enjoy the ride'
description:      'A test of what is possible, for now. Made by <a href="http://robertjbowie.com" target="_blank">@RobertBowie</a>'
url:              http://RobertBowie.github.io
baseurl:          /

author:
  name:           'Robert Bowie'
  url:            https://robertjbowie.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/RobertBowie
