# Dependencies
imarkdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            jyt0532's Blog
tagline:          'A Jekyll theme'
description:      'Life of an engineer in SV'
url:              https://jyt0532.github.io/
baseurl:          /

author:
  name:           'BoYu'
  url:            https://twitter.com/jyt0532

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/jyt0532/jyt0532.github.io
