# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mhynlo
tagline:          'Mhynlo blog'
description:      'Playing games and Developing stuff.'
url:              http://mhynlo.io
baseurl:          /

author:
  name:           'Mhynlo'
  email:          'mhynlo@mhynlo.io'
  url:            https://twitter.com/mhynlo

social:
  twitch:         https://www.twitch.tv/mhynlo
  twitter:        https://twitter.com/mhynlo
  steam:          https://steamcommunity.com/id/Mhynlo
  github:         https://github.com/mhynlo


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mhynlo/mhynlo.io
