# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            winfan
tagline:          'A blog 我只是很懒'
description:      'only want free in computer world'
url:              http://giftman.github.io
baseurl:          /

author:
  name:           'winfan'
  url:            http://giftman.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/giftman/giftman.github.io
