# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Benoit Clair
tagline:          'Personal page'
description:      'Portfolio management & computer scientist @<a href="http://edf.com" target="_blank">EDF Lab</a>.'
url:              http://bclair.eu
baseurl:          /

author:
  name:           'Benoit Clair'
  url:            https://twitter.com/benoit_clair

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/paronax/

