# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: false

# Setup
title:            Party Life Productions
tagline:          'A working group'
description:      'A brazen collaboration.'
url:              http://partylife.productions
baseurl:          /

author:
  name:           'Colin Snyder'
  url:            http://www.colingramsnyder.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/partylifeproductions/partylifeproductions.github.io
