# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            México en Datos
tagline:          ''
description:      'Análisis Exploratorio y Predictivo de Datos sobre México'
url:              https://mexicoendatos.github.io/
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mexicoendatos/Mexico-Data
