encoding:         UTF-8

# Permalinks
permalink:        /:year/:month/:day/:slug

# Gems
gems:
- jekyll-redirect-from
- jemoji

# Setup
title:            tinypalace
tagline:          'games festival'
description:      '(╯°□°）╯︵ ┻━┻'
url:              http://tinypalace.de
baseurl:

author:
  name:           'tiny'
  url:            https://twitter.com/tinytinypalace
  email:          tinypalace@posteo.de

# Custom vars

github:
  repo:           https://github.com/tinypalace/tinypalace.github.io

defaults:
  -
    scope:
      path: "/_posts/en"
    values:
      lang: en
      layout: default
  -
    scope:
      path: "/_posts/de"
    values:
      lang: de

prose:
  rooturl: '_posts'
  siteurl: 'http://tinypalace.de'
  media: 'assets/img'
  ignore:
    - 0000-01-01-index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts/de/pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "/permalink"
    _posts/de/posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    _posts/en/pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "/permalink"
    _posts/en/posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

    _posts/de:
      - name: "lang"
        field:
          element: "hidden"
          value: "de"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "name me so I know the DE/EN counterpart"
      - name: "video-id"
        field:
          element: "text"
          label: "Vimeo ID (optional)"
    _posts/en:
      - name: "lang"
        field:
          element: "hidden"
          value: "en"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "name me so I know the DE/EN counterpart"
      - name: "video-id"
        field:
          element: "text"
          label: "Vimeo ID (optional)"
