# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gaea Project
tagline:          'per Eric Parga'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hacknug.github.io/
baseurl:          /

author:
  name:           'Nestor Vera'
  url:            https://twitter.com/hack_nug

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  characters:
    output:       true
