# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Mohit Reddy'
tagline:          ''
description:      'Programmer, Night Owl.<br>Future Employee @Google, Cloud Infrastructure, Warsaw.<br>Summer 2017 (May - August) Intern @Google, Search Infrastructure, Zurich.<br>Distributed Systems, Algorithms and Data Structures, Machine Learning Enthusiast.'
url:              https://mohitreddy1996.github.io
baseurl:          /

author:
  name:           'Mohit Reddy'
  url:            'https://github.com/mohitreddy1996'

paginate:         5
gems:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          2.1.0

github:
repo:             https://github.com/mohitreddy1996/mohitreddy1996.github.io

twitter_username: MohitReddy13
github_username: mohitreddy1996
facebook_username: mohitreddy1996
googleplus_username: +MohitReddy1996 
linkedin_username: mohit-reddy-334427104