# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Gems
gems:
- jekyll-sitemap

# Setup
title:            tinypalace
tagline:          'games festival'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://tinypalace.de
baseurl:          /

author:
  name:           'tiny'
  url:            https://twitter.com/tinypalace_

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tinypalace/tinypalace.github.io

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/de
    values:
      layout: default
      lang: de
	  
# Translations
t:
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
  de:
    home:
      name: "Zuhause :)"
      url: "/de"
    about:
      name: "Ãœber uns"
      url: "/about-de/"