# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Practice Web Development
tagline:          'Practice HTML, CSS and Javascript'
description:      'Practice HTML, CSS and Javascript'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
# version:          2.1.0

# github:
  # repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown